### ISSUE TITLE
StoreDTO에서 dtoToEntity를 할 경우 에러가 납니다.

### ISSUE THREAD

**Issue by j-seon** [j-seon/yumyums#70]
## Describe the bug
StoreDTO에서 추가된 imageDTO가 null값일 경우가 있어,
StoreDTO를 Entity로 만드는 과정에서 imageDTO.dtoToEntity를 할 경우 null pointer exeption이 납니다.

### 구체적인 상황
1. PartyDTO를 Entity로 변환하려고 함
2. PartyDTO안에있는 StoreDTO를 Entity로 변환하려고 함
3. StoreDTO에서 imageDTO를 Entity로 변환하려고함 (여기서 imagDTO의 값이 없어 = null이어서 터집니다.)

```java
java.lang.NullPointerException: Cannot invoke "com.yum.yumyums.dto.ImagesDTO.dtoToEntity()" because "this.imagesDTO" is null
	at com.yum.yumyums.dto.seller.StoreDTO.dtoToEntity(StoreDTO.java:45) ~[main/:na]
	at com.yum.yumyums.dto.chat.PartyDTO.dtoToEntity(PartyDTO.java:32) ~[main/:na]
	at com.yum.yumyums.dto.chat.PartyMemberDTO.dtoToEntity(PartyMemberDTO.java:23) ~[main/:na]
```

## Additional context
dtoToEntity부분에서 imageDTO가 null일 경우의 처리가 필요해보여요!!! 수정해주세요!!!

**Comment by j-seon** [comment]
구동을 위해 임시로 if문을 넣어서 사용하고 있겠습니다!!! 처리 완료되시면 말씀해주세요 @fuzzylogicbox 

```
        if(imagesDTO != null) {
            store.setImages(imagesDTO.dtoToEntity());
        }
```
